[CFE-535] Add support for bot wide code freeze
lastquestion/steward-bot pull request #18
Opened 2020-12-16 20:46 UTC by cosmonot1

Add code freeze to repo config. Prevent adding PRs to train if code freeze is turned on and the merge head is not the specified freeze branch. Add tests. Add UI so that we can change the code freeze status.

![image](https://user-images.githubusercontent.com/7645379/102404544-b93a8400-3f9c-11eb-95d5-26ad581cf80d.png)

2020-12-16 22:10 UTC, lastquestion requested changes
This just reminds me the UI needs to be rewritten into react, 😢  

Main thing is I think this won't work with the buttons re: the mutations, see the get/set accessors. Otherwise, the UI changes are nice, can you change the POST url.

2020-12-16 22:10 UTC, lastquestion commented on src/merge.ts
> +  const { enforceCodeFreeze = false, codeFreezeBranchName = "" } = config;
Does this work actually when you change the value? You need to add mutators like for the other config values so that the UI can change it as this is a copy.

2020-12-16 22:10 UTC, lastquestion commented on src/routes.ts
> +<strong>Code freeze status: ${firstRepo ? firstRepo.enforceCodeFreeze : "unknown"}</strong>
Maybe `No repos configured` here instead of `unknown`

2020-12-16 22:10 UTC, lastquestion commented on src/routes.ts
> +<span style="color:red;font-weight:bold;">Warning: This affects ALL repositories using the PR Bot. Notify all repository owners before you enforce code freeze</span>
nit: `freeze.`

2020-12-16 22:10 UTC, lastquestion commented on src/routes.ts
> +        repos[repoName].codeFreezeBranchName = repos[repoName].codeFreezeBranchName = codeFreezeBranchName;
looks like a copy pasta error.

2020-12-16 22:10 UTC, lastquestion commented on src/routes.ts
> +  router.post("/codeFreeze", (req, res) => {
do you mind to move this into `post /<reponame>/freeze`, but leave the loop over all repos as is? e.g. the URL structure is correct but the code won't actually set it per repo yet.

2020-12-16 22:10 UTC, lastquestion commented on src/routes.ts
> +  router.post("/codeFreeze", (req, res) => {
Also make a `req.log` line statement here similar to the other router post.

2020-12-16 22:10 UTC, lastquestion commented on test/merge.test.ts
> +    test("should add branch to train to anything if enforceCodeFreeze is on and codeFreezeBranchName is unset ", async () => {
better english here? is this testing that when `enforceCodeFreeze` is on, but the branch is not set, it doesn't block anything? IMHO that's weird, if `enforceCodeFreeze` is on but no branch is set, it should reject all PRs to all branches, e.g. its eqv to paused. Or we could disallow that state and assert and error. I don't mind which.

2020-12-16 22:22 UTC, cosmonot1 commented on src/merge.ts
> +        if (enforceCodeFreeze && !targetBranch.includes(codeFreezeBranchName)) {
Fair point. the format for branch labels is `merge-target:branch-name`. I'll split on the `:` and use `===`

2020-12-16 22:28 UTC, cosmonot1 commented on test/merge.test.ts
> +    test("should add branch to train to anything if enforceCodeFreeze is on and codeFreezeBranchName is unset ", async () => {
With the new `===`, this case is no longer valid. If no merge branch is set up, we will try and `===` the empty string. and git doesn't allow branches with no name as far as i know

2020-12-17 02:16 UTC, lastquestion approved these changes
Looks fine, I'll merge and publish.

2020-12-17 02:34 UTC, merged

2020-12-17 02:35 UTC, lastquestion commented
Manually published and push tags for `+ steward-bot@0.0.3`.

Really, I should set up CI and autopublish. Coming soon....